site_name: TorchStructure
repo_url: https://github.com/lazlo-bleker/torch-structure
theme:
  logo: assets/ts_arch_light.svg
  favicon: assets/ts_arch_light.svg
  name: material
  custom_dir: overrides
  language: en
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Lato
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]
- gen-files:
    scripts:
    - docs_scripts/gen_ref_pages.py

extra_css:
  - stylesheets/extra.css
