site_name: TorchStructure
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]
- gen-files:
    scripts:
    - docs_scripts/gen_ref_pages.py 
