[project]
name = "torch_structure"
version = "0.0.1"
authors = [
    {name = "Lazlo Bleker", email = "lazlo.bleker@tum.de"}
]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "matplotlib>=3.10.1",
    "pydantic>=2.10.6",
    "scipy>=1.15.2",
]

[dependency-groups]
dev = [
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-material>=9.5.44",
    "mkdocstrings>=0.28.3",
    "pytest>=8.3.3",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.10",
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]
