[project]
name = "torch_structure"
version = "0.0.1"
authors = [
    {name = "Lazlo Bleker", email = "lazlo.bleker@tum.de"}
]
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "matplotlib>=3.9.0",
    "pydantic>=2.10.6",
    "scipy>=1.13",
]

[project.optional-dependencies]
dev = [
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-material>=9.5.44",
    "mkdocstrings[python]>=0.28.3",
    "pytest>=8.3.3",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.10",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]
