[project]
name = "torch_structure"
version = "0.1.0"
description = "A Python package for graph-based autodifferentiable structural design and engineering."
authors = [
    {name = "Lazlo Bleker"}
]
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
]

dependencies = [
    "matplotlib>=3.9.0",
    "numpy",
    "packaging",
    "scipy>=1.13",
    "torch-geometric>=2.6.1",
]

[project.urls]
Documentation = "https://lazlo-bleker.github.io/torch-structure/"
Repository = "https://github.com/lazlo-bleker/torch-structure"

[project.optional-dependencies]
dev = [
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-material>=9.5.44",
    "mkdocstrings[python]>=0.28.3",
    "pytest>=8.3.3",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.10",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]
